complete task arrays
helmq/study pull request #1
Opened 2019-03-21 03:50 UTC by helmq

2019-03-21 11:16 UTC, Andrew8xx8 requested changes

2019-03-21 11:16 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        max = array.max
Нужно реализовать поиск максимума самому

2019-03-21 11:16 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +      def search_recursive(array, query)
Зачем две разные функции?
Зачем заворачивать в лямбду всю функцию, елси можно функцию как таковую саму из себя вызвать без создания лишней функции?

2019-03-21 12:18 UTC, helmq commented on test/exercise/arrays/solution.rb
> +      def search_recursive(array, query)
`def search(array, query, first = 0, last = array.size - 1)`
Нормально ли так в аргументах писать?

2019-03-22 18:59 UTC, artempartos commented
👍

2019-03-23 16:05 UTC, merged